#define ZR_VER_PRODUCT_NAME     "Zombie:Reloaded"
#define ZR_VER_COPYRIGHT        "Copyright (C) 2009  Greyscale, Richard Helgeby"
#define ZR_VER_VERSION          VERSION
#define ZR_VER_BRANCH           "zr-3.0-b2"
#define ZR_VER_REVISION         "Unofficial build - based on 675:ffaded7c355f"
#define ZR_VER_LICENSE          "GNU GPL, Version 3"
#define ZR_VER_DATE             "Tue, 27 Dec 2011 09:15:58 +0100"
